
<?php
/**
 * @var \Gab\Dropshipping\Block\Adminhtml\System\Config\TestButton $block
 */
?>
<div class="actions actions-test-button">
    <?= $block->getButtonHtml() ?>
</div>

<div id="test-api-connection-result" style="margin-top: 10px; display: none;"></div>

<script type="text/x-magento-init">
    {
        "#test_api_connection_button": {
            "Gab_Dropshipping/js/test-api-connection": {
                "ajaxUrl": "<?= $block->escapeJs($block->getAjaxUrl()) ?>"
        }
    }
}
</script>
